name: 'deploy-site'
on:
    push:
        branches:
            - main
jobs:
    run-deployment:
        name: 'run-deployment'
        runs-on: ubuntu-latest
        steps:
            - id: setup-node
              name: 'Setup Node 18'
              uses: actions/setup-node@v2
              with:
                  node-version: '18'
            - id: install-yarn
              name: 'Install Yarn'
              run: npm install --global yarn
            - id: pull-latest-from-main
              name: 'Get latest codebase from main'
              uses: actions/checkout@v2
              with:
                  ref: main
            - id: run-build
              name: 'Run Build'
              run: |
                  yarn
                  yarn build
            - id: copy-dist-in-temp
              name: 'Copy artifacts to Temp'
              run: |
                  mkdir /tmp/www
                  cp -r dist/* /tmp/www/.
            - id: checkout-deployment
              name: 'Checkout deployment branch'
              uses: actions/checkout@v2
              with:
                  ref: deployment
            - id: update-deployment-branch
              name: 'Update deployment branch'
              run: |
                  rm -rf ./*
                  cp -r /tmp/www/* .
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git add .
                  git commit -m "deploying on `date +"%d-%m-%Y %H:%M %Z"`"
                  git push -f
